version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd chatter-backend
      - npm install

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - "chatter-backend/dist/**/*"
